### ISSUE TITLE
Close button mis-aligns header text

### ISSUE THREAD

**Issue by jrauh** [samaritanministries/dash-modal.js#11]
https://github.com/samaritanministries/dash-modal.js/blob/b3244a19e7066c1492f3ada6ecb81f6d973ed980/styles/dash-modal.scss#L56

Add margin-left: -2rem to the close button to bring the text back.
Also add top: 0.75rem instead of 1rem to better position.

**Comment by aknobloch3** [comment]
Fixed this with `v3.0.3`
