### ISSUE TITLE
Support for dynamic width

### ISSUE THREAD

**Issue by chandlerroth** [samaritanministries/dash-modal.js#4]
It would be great if we could have the ability to set the width of a particular modal. Perhaps a structure like this would work (in the options)

`max-width: '24rem'`

**Comment by jrauh** [comment]
I'd like the ability to add a class into the "dash-modal" element to style a specific modal within an app.

**Comment by blang32** [comment]
Joe and I are addressing all of the issues on our component projects. Do you have everything you need to style these modals appropriately, or should we leave some of these issues open?
